#!/bin/bash
# Code from https://github.com/Kagami/mpv.js/blob/master/scripts/collect-dylib-deps.sh

set -ex
cd "$( dirname "${BASH_SOURCE[0]}" )"
rm -rf dist_libs
mkdir dist_libs

copy_deps() {
  local dep=$1
  local depname=$(basename $dep)
  [[ -e dist_libs/$depname ]] || install -m755 $dep dist_libs
  otool -L $dep | awk '/\/usr\/local.*\.dylib /{print $1}' | while read lib; do
    local libname=$(basename $lib)
    [[ $depname = $libname ]] && continue
    echo $libname
    install_name_tool -change $lib @executable_path/$libname dist_libs/$depname
    [[ -e dist_libs/$libname ]] && continue
    install -m755 $lib dist_libs
    copy_deps $lib
  done
}

set +x
copy_deps mpv/build/libmpv.1.dylib
set -x